In [1]:
import tensorflow as tf
import numpy as np

from __future__ import absolute_import, division, print_function

In [2]:
test = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
test

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [3]:
np.flip(test, 1).ravel()

array([3, 4, 1, 2, 7, 8, 5, 6])

In [31]:
def init_board():
    board = np.zeros((8, 8, 6), dtype=np.int8)
    
    # Pawns
    board[1, :, 0] = -1
    board[6, :, 0] = 1
    
    # Medium
    for j in range(3):
        board[0, [j, 7-j], j+1] = -1
        board[7, [j, 7-j], j+1] = 1
    
    # Queens
    board[0, 3, 4] = -1
    board[7, 3, 4] = 1
    
    # Kings
    board[0, 4, 5] = -1
    board[7, 4, 5] = 1
    
    return board

In [5]:
board =init_board()

In [6]:
import string, re

In [7]:
move = "Nxf5+"
pattern = re.compile("[\Wx]+") 
pattern.sub("", move)

'Nf5'

In [8]:
def parse_move(move):
    
    # Remove capture/check notation (x/+)
    pattern = re.compile("[\Wx]+") 
    move = pattern.sub("", move)    
    
    piece_dict = {"R": 1, "N": 2, "B": 3, "Q": 4, "K": 5}
    
    # Identify piece type
    if move[0].isupper():
        d = piece_dict[move[0]]
        move = move[1:]
    else:
        d = 0
        
    # Check for ambiguity in move
    if len(move) == 3:
        ambig = move[0]
        move = move[1:]
    elif len(move) > 3:
        return -1
    else:
        ambig = None
     
    
    rank_dict = {"a": 7, "b": 6, "c": 5, "d": 4, "e": 3, "f": 2, "g": 1, "h": 0}
    
    r, f = rank_dict[move[0]], int(move[1])-1
    
    return [r, f, d, ambig]

In [9]:
parse_move("Kxa4")

[7, 3, 5, None]

In [10]:
board = init_board()

In [11]:
def unroll(board):
    return board.ravel()

In [12]:
unroll(board)

array([ 0, -1,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0, -1,  0,
        0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,
        0,  0,  0,  0, -1,  0,  0,  0,  0, -1,  0,  0,  0,  0, -1,  0,  0,
        0,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,
        0,  0,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0, -1,
        0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [13]:
def move_R(to, player):
    r, f, d, ambig = to
   
    if np.array([board[:, :, d] == player]).sum() == 1:
        return move_simple(to, player)
        
    elif np.array([board[:, f, d] == player]).sum() == 1:
        board[:, f, d] = np.multiply(board[:, f, d],
                                     np.array([board[:, f, d] != player]))
        
    elif np.array([board[r, :, d] == player]).sum() == 1:
        board[r, :, d] = np.multiply(board[r, :, d],
                                     np.array([board[r, :, d] != player]))
                
    else:
        try:
            a = int(ambig)-1
            board[:, a, d] = np.multiply(board[:, a, d],
                                         np.array([board[:, a, d] != player]))
            
        except ValueError:
            rank_dict = {"a": 7, "b": 6, "c": 5, "d": 4, "e": 3, "f": 2, "g": 1, "h": 0}
            a = rank_dict(ambig)
            board[a, :, d] = np.multiply(board[a, :, d],
                                         np.array([board[a, :, d] != player]))
        
    board[r, f, d] = player
        

In [14]:
board = init_board()
move = parse_move("R8a5")
print(move)
move_R(move, 1)
board[:, :, 1]

[7, 4, 1, '8']


array([[-1,  0,  0,  0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  1,  0,  0,  0]], dtype=int8)

In [15]:
[list(range(0, 3)), 10]

[[0, 1, 2], 10]

In [16]:
r = ["a", "b", "c", "d", "e", "f", "g", "h"]
f = list(range(1, 9))

move = "e4"

In [17]:
def find_diags(to):
    """ Finds squares on both diagonals that target square lies on """
    r, f, d, ambig = to
    
    diags = set()
    
    # Down-left    
    r_, f_ = r, f
    while r_ >= 0 and f_ <= 7:
        diags.add((r_, f_))
        r_ -= 1
        f_ += 1
    # Up-right
    r_, f_ = r, f
    while f_ >= 0 and r_ <= 7:
        diags.add((r_, f_))
        r_ += 1
        f_ -= 1    
    # Down-right
    r_, f_ = r, f
    while max(r_, f_) <= 7:
        diags.add((r_, f_))
        r_ += 1
        f_ += 1
    # Up-left
    r_, f_ = r, f
    while min(r_, f_) >= 0:
        diags.add((r_, f_))
        r_ -= 1
        f_ -= 1  
        
    return list(diags)

In [18]:
find_diags([3, 5, 2, None])

[(3, 5),
 (2, 6),
 (1, 3),
 (4, 6),
 (7, 1),
 (0, 2),
 (4, 4),
 (5, 7),
 (6, 2),
 (1, 7),
 (2, 4),
 (5, 3)]

In [19]:
def move_B(to, player):
    r, f, d, ambig = to
   
    # If there's only one piece of that type
    if np.array([board[:, :, d] == player]).sum() == 1:
        return move_simple(to, player)
    
    # Only one bishop on each square colour; so just wipe both diagonals        
    else:
        diags = find_diags(to)
        for square in diags:
            r_, f_ = square
            if board[r_, f_, 3] == player:
                board[r_, f_, 3] = 0
        
    board[r, f, d] = player

In [20]:
board = init_board()
board[:, :, 3]

array([[ 0,  0, -1,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  1,  0,  0]], dtype=int8)

In [21]:
move_B(parse_move("Bf8"), 1)
board[:, :, 3]
move_B(parse_move("Bg2"), -1)
board[:, :, 3]

array([[ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0]], dtype=int8)

In [22]:
import itertools as it
list(it.permutations([-2, -1, 1, 2], 2))

[(-2, -1),
 (-2, 1),
 (-2, 2),
 (-1, -2),
 (-1, 1),
 (-1, 2),
 (1, -2),
 (1, -1),
 (1, 2),
 (2, -2),
 (2, -1),
 (2, 1)]

In [23]:
def move_N(to, player):
    r, f, d, ambig = to
    
    # If there's only one piece of that type
    if np.array([board[:, :, d] == player]).sum() == 1:
        return move_simple(to, player)
    
    # Check to see if it's the only one in potential origin squares
    origins = [[2, 1], [2, -1], [1, 2], [1, -2],
               [-1, 2], [-1, -2], [-2, 1], [-2, -1]]
    
    count = 0
    
    for og in origins:
        r_, f_ = np.add([r, f], og)
        if 0 <= r_ <= 7 and 0 <= f_ <= 7:
            if board[r_, f_, d] == player:
                count += 1
    print(count)            
    if count == 1:
        for og in origins:
            r_, f_ = np.add([r, f], og)
            if 0 <= r_ <= 7 and 0 <= f_ <= 7:
                if board[r_, f_, d] == player:
                    board[r_, f_, d] = 0
                    
    # Use the disambiguator            
    else:
        try:
            a = int(ambig)-1
            board[:, a, d] = np.multiply(board[:, a, d],
                                         np.array([board[:, a, d] != player]))
            
        except ValueError:
            a = rank_dict[ambig]
            board[a, :, d] = np.multiply(board[a, :, d],
                                         np.array([board[a, :, d] != player]))
    
    board[r, f, d] = player
    

In [24]:
board = init_board()
board[:, :, 2]

array([[ 0, -1,  0,  0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  1,  0]], dtype=int8)

In [25]:
rank_dict = {"a": 7, "b": 6, "c": 5, "d": 4, "e": 3, "f": 2, "g": 1, "h": 0}
move_N(parse_move("Nc6"), 1)
board[:, :, 2]

move_N(parse_move("Ncb4"), 1)
board[:, :, 2]

1
2


array([[ 0, -1,  0,  0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [26]:
parse_move("Ncb4")

[6, 3, 2, 'c']

In [27]:
L = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
M = [1, 2, 3, 4, 5, 6, 7, 8]
m = L.index('d')
n = M.index(6)
if m > n:
  m, n = (m - n), 0
else:
  m, n = 0, (n - m)
print(list(zip(L[m:], M[n:])))

[('a', 3), ('b', 4), ('c', 5), ('d', 6), ('e', 7), ('f', 8)]


In [49]:
def move_P(to, player):
    r, f, d, ambig = to
    
    if ambig is not None:
        a = rank_dict[ambig]
        board[r+player, a, d] = 0

    elif board[r+player, f, d] == player:
        board[r+player, f, d] = 0
        
    else:
        board[r+2*player, f, d] = 0
        
    board[r, f, d] = player

In [50]:
board = init_board()
board[:, :, 0]

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [51]:
move_P(parse_move("c1"), 1)
board[:, :, 0]

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  1,  1,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [52]:
move_P(parse_move("d6"), 1)
board[:, :, 0]

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  1,  1,  1,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [53]:
move_P(parse_move("e4"), -1)
board[:, :, 0]

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1, -1,  0, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  1,  1,  1,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [54]:
move_P(parse_move("e5"), -1)
board[:, :, 0]

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1, -1,  0,  0, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  1,  1,  1,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [55]:
move_P(parse_move("c1"), 1)
board[:, :, 0]

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1, -1,  0,  0, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  1,  1,  1,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [61]:
f_dict = {"a": 0, "b": 1, "c": 2, "d": 3, "e": 4, "f": 5, "g": 6, "h": 7}

def parse_move(move):
    
    # Remove capture/check notation (x/+)
    pattern = re.compile("\+") 
    move = pattern.sub("", move)    
    
    piece_dict = {"R": 1, "N": 2, "B": 3, "Q": 4, "K": 5}
    
    # Identify piece type
    if move[0].isupper():
        d = piece_dict[move[0]]
        move = move[1:]
    else:
        d = 0
        if "x" in move:
            ambig = move[0]
            move = move[2:]
    
    # Check for ambiguity in move
    if len(move) == 3:
        ambig = move[0]
        move = move[1:]
    elif len(move) > 3:
        return -1
    else:
        ambig = None
    
    r, f = int(move[1])-1, f_dict[move[0]]
    
    return [r, f, d, ambig]

In [62]:
parse_move("c4")

[3, 2, 0, None]