In [2]:
import tensorflow as tf
import numpy as np

from __future__ import absolute_import, division, print_function

In [5]:
range(3, NaN)

NameError: name 'NaN' is not defined

In [14]:
test = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
test

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
np.flip(test, 1).ravel()

array([3, 4, 1, 2, 7, 8, 5, 6])

In [216]:
def init_board():
    board = np.zeros((8, 8, 6), dtype=np.int8)
    
    # Pawns
    board[1, :, 0] = -1
    board[6, :, 0] = -1
    
    # Medium
    for j in range(3):
        board[0, [j, 7-j], j+1] = -1
        board[7, [j, 7-j], j+1] = 1
    
    # Queens
    board[0, 3, 4] = -1
    board[7, 3, 4] = 1
    
    # Kings
    board[0, 4, 5] = -1
    board[7, 4, 5] = 1
    
    return board

In [217]:
board =init_board()

In [218]:
import string, re

In [219]:
move = "Nxf5+"
pattern = re.compile("[\Wx]+") 
pattern.sub("", move)

'Nf5'

In [220]:
def parse_move(move):
    
    # Strip down to just the move
    pattern = re.compile("[\Wx]+") 
    move = pattern.sub("", move)
    
    piece_dict = {"R": 1, "N": 2, "B": 3, "Q": 4, "K": 5}
    
    if move[0].isupper():
        d = piece_dict[move[0]]
        move = move[1:]
    else:
        d = 0
    
    rank_dict = {"a": 7, "b": 6, "c": 5, "d": 4, "e": 3, "f": 2, "g": 1, "h": 0}
    
    r, f = rank_dict[move[0]], int(move[1])-1
    
    return (r, f, d)


def move_KQ(to, player=1):
    board[:, :, 5] = np.multiply(board[:, :, 5],
                                 np.array([board[:, :, 5] != player]))
    board[to] = player

In [221]:
parse_move("Kxa4")

(7, 3, 5)

In [252]:
board = init_board()

In [223]:
to = parse_move("Kg6")
move_KQ(to, -1)
board[:, :, 5]

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0]], dtype=int8)

In [224]:
def unroll(board):
    return board.ravel()

In [228]:
unroll(board)

array([ 0, -1,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0, -1,  0,
        0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,
        0,  0,  0,  0, -1,  0,  0,  0,  0, -1,  0,  0,  0,  0, -1,  0,  0,
        0,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,
        0,  0,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0, -1,
        0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [246]:
def move_R(to, player):
    r, f, d = to
   
    if (np.array([board[:, :, d] == player]).sum() == 1):
        move_simple(to, player)
        
    elif (np.array([board[r, :, d] == player]).sum() == 1):
        board[r, :, d] = np.multiply(board[r, :, d],
                                     np.array([board[r, :, d] != player]))
        board[r, f, d] = player
        
    elif (np.array([board[:, f, d] == player]).sum() == 1):
        board[:, f, d] = np.multiply(board[:, f, d],
                                     np.array([board[:, f, d] != player]))
        board[r, f, d] = player
        
    else:
        return -1

In [258]:
move = parse_move("Rd1")
move_R(move, 1)
board[:, :, 1]

array([[-1,  0,  0,  0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1]], dtype=int8)

In [257]:
move

(4, 3, 1)